server:
  port: 8662

spring:
  application:
    name: gateway-service
eureka:
  client:
  registerWithEureka: false
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

zuul:
  host:
    conect-timeout-millis: 500000
    socker-timeout-millis: 500000
  ignoredServices: '*'
  routes:
    sampleapp:
      path: /sample-service/**
      serviceId: sample-service
      # stripPrefix: true
      #url: http://localhost:5600
